version: '3.8'
services:
  app:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    volumes:
      - ./:/workspace
      - .devcontainer/scripts/.bashrc:/home/gopher/.bashrc:ro
      - .devcontainer/scripts/git-completion.bash:/home/gopher/.git-completion.bash:ro
